POST localhost:9000/auth/login
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "password123"
}

###
POST localhost:9000/auth/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDE0OTVjZWY2NGNmMzdkOTYyNDI4OTMiLCJzbHVnIjoiam9obmRvZSIsImZpcnN0TmFtZSI6IkpvaG4iLCJsYXN0TmFtZSI6IkRvZSIsImVtYWlsIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJ1c2VyTmFtZSI6ImpvaG5kb2UiLCJwYXNzd29yZCI6IiQyYiQxMCRpTnNhYWkvY3k0QjJZdlROUjJ5SldPVEs0Q0YvQ2FINVhuQzd0RDdWV1pxZ3B4ZnZtcktzcSIsImJpcnRoRGF0ZSI6IjE5OTAtMDEtMDFUMDA6MDA6MDAuMDAwWiIsIm1vYmlsZU51bWJlciI6Iis0MjE5NTA4OTI2NjIiLCJjaXR5IjoiTmV3IFlvcmsiLCJ1cGRhdGVkQXQiOiIyMDIzLTAzLTE3VDE2OjMxOjA4Ljg2NloiLCJjcmVhdGVkQXQiOiIyMDIzLTAzLTE3VDE2OjMxOjA4Ljg2NloiLCJhY2NvdW50VHlwZSI6IjY0MTQ4YzgyNjdkY2FmYmRhZDQzYjNkMCIsImFjdGl2ZVByb2ZpbGUiOmZhbHNlLCJjb250cmFjdHMiOltdLCJwcm9maWxlIjoiNjQxNDk1Y2VmNjRjZjM3ZDk2MjQyODk0IiwiX192IjowLCJpYXQiOjE2NzkzMzM2NTN9.clDeGdj4qiOBcmPOZbSN4LM_LiEQUE7yV73m8bzubJ4"
}
